const questions = [

{ id: "Q1", question: "After spending, what do you ACTUALLY feel?", options: ["No regret","Slight doubt","Regret","Strong regret"] },
{ id: "Q2", question: "When you OVERSPEND, what do you do NEXT?", options: ["Ignore it","Think about it","Feel bad","Regret it"] },
{ id: "Q3", question: "After spending, how do you JUSTIFY it?", options: ["Makes sense","Probably fine","Not sure","Regret it"] },
{ id: "Q4", question: "When spending, what makes you EXCEED limits?", options: ["Always within","Sometimes within","Often exceed","Always exceed"] },
{ id: "Q5", question: "When you use your card, what do you ACTUALLY do?", options: ["Fully planned","Mostly planned","Sometimes impulse","Fully impulse"] },
{ id: "Q6", question: "When you use money daily, what do you ACTUALLY do?", options: ["Track everything","Some tracking","Guess","No tracking"] },
{ id: "Q7", question: "When you spend, what do you ACTUALLY do?", options: ["Track everything","Rough track","Guess","No tracking"] },
{ id: "Q8", question: "What SMALL spending do you IGNORE the most?", options: ["Coffee","Food","Subscriptions","Everything"] },
{ id: "Q9", question: "When using subscriptions, what do you ACTUALLY do?", options: ["Well managed","Some","Too many","No control"] },
{ id: "Q10", question: "When you get paid, what do you ACTUALLY do FIRST?", options: ["Save first","Think a bit","Spend first","No plan"] },

{ id: "Q11", question: "When you OVERSPEND, what do you BLAME?", options: ["Nothing","Situation","Others","Myself"] },
{ id: "Q12", question: "When STRESSED, what do you do with MONEY?", options: ["Never spend","Think about it","Spend a bit","Spend a lot"] },
{ id: "Q13", question: "When money runs LOW, what do you CUT FIRST?", options: ["Nothing","Small spending","Important spending","Everything"] },
{ id: "Q14", question: "Before buying, what do you SKIP FIRST?", options: ["Nothing","Comparing","Thinking","Everything"] },
{ id: "Q15", question: "When buying online, what do you ACTUALLY do?", options: ["Think first","Check a bit","Click fast","Buy instantly"] },
{ id: "Q16", question: "When checking your bank, what do you IGNORE?", options: ["Nothing","Small things","Most things","Everything"] },
{ id: "Q17", question: "When money comes in, what do you FORGET FIRST?", options: ["Nothing","Saving","Planning","Everything"] },
{ id: "Q18", question: "When getting extra money, what do you ACTUALLY do FIRST?", options: ["Save first","Think about it","Spend first","Spend without thinking"] },
{ id: "Q19", question: "When planning money, what do you ACTUALLY do?", options: ["Clear plan","Basic plan","Thinking","No plan"] },
{ id: "Q20", question: "When setting a budget, what do you ACTUALLY do?", options: ["Strict","Loose","Trying","None"] },

{ id: "Q21", question: "When trying to cut spending, what do you STRUGGLE with?", options: ["Easy","Manageable","Hard","Impossible"] },
{ id: "Q22", question: "When managing expenses, where do you LOSE CONTROL?", options: ["Very controlled","Mostly","Struggling","Out of control"] },
{ id: "Q23", question: "When emotions affect spending, what do you ACTUALLY do?", options: ["Never affects me","A little","Often","Always"] },
{ id: "Q24", question: "When spending to IMPRESS, what do you ACTUALLY do?", options: ["Never do it","Think about it","Do it sometimes","Do it often"] },
{ id: "Q25", question: "When spending for HAPPINESS, what do you CHOOSE?", options: ["Always worth it","Sometimes","Rarely","Not worth it"] },
{ id: "Q26", question: "When reviews conflict, what do you FOLLOW?", options: ["Best rating","Most reviews","Gut feeling","Just buy"] },
{ id: "Q27", question: "How long do you KEEP subscriptions you don’t use?", options: ["Cancel fast","Keep a bit","Keep long","Never cancel"] },
{ id: "Q28", question: "When you see a SALE, what do you IGNORE?", options: ["Nothing","Price","Need","Everything"] },
{ id: "Q29", question: "When checking your balance, what do you AVOID seeing?", options: ["Nothing","Small drops","Big spending","Everything"] },
{ id: "Q30", question: "When delaying a purchase, what makes you GIVE IN?", options: ["Nothing","Small urge","Strong urge","Always give in"] },

{ id: "Q31", question: "When trying to save automatically, what STOPS you?", options: ["Nothing","Forget it","Hard to keep","Never works"] },
{ id: "Q32", question: "When bills come in, what do you DELAY FIRST?", options: ["Nothing","Small bills","Big ones","Everything"] },
{ id: "Q33", question: "When tracking spending, what makes you STOP?", options: ["Never stop","Get tired","Lose track","Give up"] },
{ id: "Q34", question: "When avoiding spending, what makes you BREAK it?", options: ["Always avoid","Sometimes","Rarely","Never"] },
{ id: "Q35", question: "When dealing with debt, what do you ACTUALLY do?", options: ["Always avoid","Sometimes","Rarely","Always in debt"] },
{ id: "Q36", question: "When spending with others, what do you ACTUALLY do?", options: ["Fair balance","Mostly fair","Sometimes overspend","No control"] },
{ id: "Q37", question: "When choosing cash or card, what do you USE?", options: ["Mostly cash","Balanced","Mostly card","Only card"] },
{ id: "Q38", question: "When saving money, what do you ACTUALLY do?", options: ["Always consistent","Try to save","Save sometimes","Rarely save"] },
{ id: "Q39", question: "When saving for emergencies, what do you DO FIRST?", options: ["Always ready","Somewhat ready","Barely ready","Not ready"] },
{ id: "Q40", question: "When you DELAY saving, what do you TELL yourself?", options: ["Nothing","Start soon","Later is fine","No need"] },

{ id: "Q41", question: "When planning big purchases, what do you DO FIRST?", options: ["Plan ahead","Rough idea","Decide later","No plan"] },
{ id: "Q42", question: "When thinking about living costs, what do you ACTUALLY CHECK?", options: ["Very clear","Somewhat clear","Vague","No idea"] },
{ id: "Q43", question: "When reviewing expenses, what do you CHECK?", options: ["Check everything","Check some","Ignore small","Ignore most"] },
{ id: "Q44", question: "When you think about money, what do you CHOOSE?", options: ["Security first","Balance","Enjoyment","Just spending"] },
{ id: "Q45", question: "When thinking about your future, what do you DELAY most?", options: ["Nothing","Small plans","Big plans","Everything"] },
{ id: "Q46", question: "When spending on yourself, what do you ACTUALLY DO?", options: ["Balanced","Spend a bit","Spend more","Overspend"] },
{ id: "Q47", question: "When spending on learning, what do you HESITATE about?", options: ["Nothing","Price","Value","Everything"] },
{ id: "Q48", question: "When investing in yourself, what do you ACTUALLY DO?", options: ["Invest in myself","Think about it","Delay it","Ignore it"] },
{ id: "Q49", question: "When you NEED money, what do you DO FIRST?", options: ["Use my own","Cut spending","Think about borrowing","Borrow right away"] },
{ id: "Q50", question: "When someone asks you for money, what do you DO?", options: ["Help right away","Think about it","Rarely help","Say no"] },

{ id: "Q51", question: "When facing unexpected costs, what do you DO FIRST?", options: ["Always prepared","Somewhat ready","Barely ready","Not prepared"] },
{ id: "Q52", question: "When thinking about emergencies, what do you PREPARE?", options: ["Fully ready","Somewhat","Barely","Not ready"] },
{ id: "Q53", question: "When choosing wants vs needs, what do you CHOOSE?", options: ["Mostly needs","Balanced","Mostly wants","Only wants"] },
{ id: "Q54", question: "When you see others spending, what do you FEEL?", options: ["Nothing","A little pressure","Comparison","Need to match"] },
{ id: "Q55", question: "How do you ACTUALLY feel about your money habits?", options: ["Very good","Okay","Not good","Bad"] },
{ id: "Q56", question: "When spending, what makes you LOSE CONTROL?", options: ["Full control","Mostly control","Sometimes lose","No control"] }

];
